

raw_data = {'code': 'UNKNOWN',
            'data': {'completeTests': [{'activatedOn': None,
                                        'activationCode': 'N4Y9X7S2E6M6R9L',
                                        'guid': 'B0004280-63E9-45B2-9588-1E7AE812CC1D',
                                        'lastUpdated': 1490050775003,
                                        'matchingParticipant': True,
                                        'notificationCount': None,
                                        'processingBegan': None,
                                        'productId': 2,
                                        'recollectable': False,
                                        'role': 'Subject',
                                        'selfTest': True,
                                        'shippedToLabOn': None,
                                        'state': 'Complete',
                                        'testAdminDisplayName': 'Matt Hannan',
                                        'testAdminUcdmId': '012BC9DC-0003-0000-0000-000000000000',
                                        'testSubject': {'adminDisplayName': 'Matt Hannan',
                                                        'displayName': 'Matt Hannan',
                                                        'gender': 'MALE',
                                                        'givenNames': 'Matt',
                                                        'privateName': 'M. H. ',
                                                        'surname': 'Hannan',
                                                        'ucdmId': '012BC9DC-0003-0000-0000-000000000000'},
                             'usersSelfTest': True},
                            {'activatedOn': None,
                             'activationCode': 'H7Z3R5B7C7D2G4X',
                             'guid': 'E14CAA33-B0C8-4A11-A721-26F2C5822671',
                             'lastUpdated': 1405852313860,
                             'matchingParticipant': True,
                             'notificationCount': None,
                             'processingBegan': None,
                             'productId': 2,
                             'recollectable': False,
                             'role': 'Guest',
                             'selfTest': True,
                             'shippedToLabOn': None,
                             'state': 'Complete',
                             'testAdminDisplayName': 'goldenbear9741',
                             'testAdminUcdmId': '02A24727-0006-0000-0000-000000000000',
                             'testSubject': {'adminDisplayName': 'goldenbear9741',
                                             'displayName': 'goldenbear9741',
                                             'gender': 'FEMALE',
                                             'givenNames': 'Charlotte',
                                             'privateName': 'C. A. ',
                                             'surname': 'Anderson',
                                             'ucdmId': '02A24727-0006-0000-0000-000000000000'},
                             'usersSelfTest': False},
                            {'activatedOn': None,
                             'activationCode': 'U2F4U9K8D9H8Q6Z',
                             'guid': '372B8395-A9E7-49ED-9020-71252C4D4917',
                             'lastUpdated': 1445580240100,
                             'matchingParticipant': True,
                             'notificationCount': None,
                             'processingBegan': None,
                             'productId': 2,
                             'recollectable': False,
                             'role': 'Guest',
                             'selfTest': False,
                             'shippedToLabOn': None,
                             'state': 'Complete',
                             'testAdminDisplayName': None,
                             'testAdminUcdmId': '015AE54B-0002-0000-0000-000000000000',
                             'testSubject': {'adminDisplayName': 'A. O. ',
                                             'displayName': 'A. O. ',
                                             'gender': 'FEMALE',
                                             'givenNames': 'AnnMarie',
                                             'privateName': 'A. O. ',
                                             'surname': "O'Sullivan",
                                             'ucdmId': None},
                             'usersSelfTest': False}],
          'hasSelfTest': True,
          'inProgressTests': [{'activatedOn': 1520269866653,
                               'activationCode': 'H9G2X9Y2R8C2P3Q',
                               'guid': '934815A7-BA79-4346-9D57-C5CE683688B6',
                               'lastUpdated': 1522352138060,
                               'matchingParticipant': True,
                               'notificationCount': None,
                               'processingBegan': 1522352138067,
                               'productId': 2,
                               'recollectable': False,
                               'role': 'Admin',
                               'selfTest': True,
                               'shippedToLabOn': 1520964689487,
                               'state': 'InProcess',
                               'testAdminDisplayName': 'MIKE HANNAN',
                               'testAdminUcdmId': '012BC9DC-0003-0000-0000-000000000000',
                               'testSubject': {'adminDisplayName': 'MIKE '
                                                                   'HANNAN',
                                               'displayName': 'MIKE HANNAN',
                                               'gender': 'MALE',
                                               'givenNames': 'MIKE',
                                               'privateName': 'M. H. ',
                                               'surname': 'HANNAN',
                                               'ucdmId': '04D89930-0006-0000-0000-000000000000'},
                               'usersSelfTest': False}],
          'recollectTests': []},
 'status': 'SUCCESS'}

#'data': {'completeTests': [
for k, v in raw_data:
    print(raw_data['data'])